### PR TITLE
Fix EI instance list bug

### LINKED ISSUE #236: EI Instance list functionality do not use newly added EI instances in application.properties
### Description
Today EI Frontend never reads EI instance list from application.properties if a EI Instance list file exists in $USER dir.
If EI frontend is restarted with new EI instances in application.properties, these Instances will never be used since EI Frontend always reads EI Instance file if it exist instead of reading application.properties EI Instance lists.

Change so it always reads the applications.properties EI Instance list before reading the EI Instances file. Only custom created/added EI Instances should be added to the file.

### Motivation
New EI instances that has been added to application.properties is never read, we can't have it like this.

### PR DESCRIPTION
**Pull request by e-edling-ericsson**
### Applicable Issues

closes #236
### Description of the Change

- It will now only by possible to add instances in the application.properties
  file.
- Fix relevant tests
### Benefits

It will now be possible to add instances in the application.properties file even if a instances file exists.
### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Erik Edling erik.edling@ericsson.com

### CODE REVIEW

File: src/main/java/com/ericsson/ei/frontend/utils/BackEndInstanceFileUtils.java [hunk 1]
```diff
@@ -34,121 +30,41 @@
...
+    public void backEndInstanceFileUtils() {
+        try {
+            LOG.info("Initiating BackEndInstanceFileUtils.");
 
-            Boolean eiHomeExists = Files.isDirectory(Paths.get(eiHome));
-            if (!eiHomeExists) {
-                createEiHomeFolder(eiHome);
-            }
+            // Use home folder if a specific backendInstancesFilePath isn't provided
+            boolean useUserHomeDirectory = (backendInstancesFilePath == null || backendInstancesFilePath.isEmpty());
```
Comment (SantoshNC68) [inline src/main/java/com/ericsson/ei/frontend/utils/BackEndInstanceFileUtils.java]: this variables can be final as they are not modified

Comment (SantoshNC68) [reply src/main/java/com/ericsson/ei/frontend/utils/BackEndInstanceFileUtils.java]: check in the other places also where we don't modify the variables.

Comment (e-edling-ericsson) [reply src/main/java/com/ericsson/ei/frontend/utils/BackEndInstanceFileUtils.java]: Oh ye, will do 👍

File: src/systemtest/resources/system-test.properties [hunk 2]
```diff
@@ -23,7 +23,7 @@ remrem.publish.url:http://publish:8080
 ## Internal url is used when frontend needs to trigger a job
 ## when a subscription has been fulfilled.
 
-jenkins.external.url:http://localhost:8082
-jenkins.internal.url:http://jenkins:8080
+jenkins.external.url:http://10.0.2.15:8082
```
Comment (e-edling-ericsson) [inline src/systemtest/resources/system-test.properties]: Changing these back to localhost

File: src/functionaltest/resources/functional-test.properties [hunk 3]
```diff
@@ -1 +1,4 @@
 test.selenium.firefox.BZip2File.url.linux = https://ftp.mozilla.org/pub/firefox/releases/61.0.1/linux-x86_64/en-GB/firefox-61.0.1.tar.bz2
+ei.backend.instances.list.json.content=[{"name":"EI-Backend-1","host":"localhost","port":8070,"contextPath":"","https":false,"defaultBackend":true}, {"name":"EI-Backend-2","host":"localhost","port":8077,"contextPath":"","https":false,"defaultBackend":false}, {"name":"EI-Backend-3","host":"localhost","port":8078,"contextPath":"","https":false,"defaultBackend":true}]
```
Comment (tobiasake) [inline src/functionaltest/resources/functional-test.properties]: I think you can make each line in this json list by adding slash "\" in end of each line, e.g.:
 ei.backend.instances.list.json.content=[{"name":"EI-Backend-1","host":"localhost","port":8070,"contextPath":"","https":false,"defaultBackend":true},\
 {"name":"EI-Backend-2","host":"localhost","port":8077,"contextPath":"","https":false,"defaultBackend":false},\
{"name":"EI-Backend-3","host":"localhost","port":8078,"contextPath":"","https":false,"defaultBackend":true}]

File: src/integrationtest/resources/integration-test.properties [hunk 4]
```diff
@@ -113,6 +113,10 @@ spring.mail.properties.mail.smtp.starttls.enable: false
 #er.url: http://localhost:8080/eventrepository/search/
 er.url:
 
+######## EI Default Back-Ends
+ei.backend.instances.list.json.content=[{"name":"EI-Backend-1","host":"localhost","port":8070,"contextPath":"","https":false,"defaultBackend":true}, {"name":"EI-Backend-2","host":"localhost","port":8077,"contextPath":"","https":false,"defaultBackend":false}, {"name":"EI-Backend-3","host":"localhost","port":8078,"contextPath":"","https":false,"defaultBackend":true}]
```
Comment (tobiasake) [inline src/integrationtest/resources/integration-test.properties]: same comment here.

**Comment by a-breid-ericsson** [comment]
Is change description valid?

File: src/main/java/com/ericsson/ei/frontend/utils/BackEndInstancesHandler.java [hunk 5]
```diff
@@ -0,0 +1,142 @@
...
+    public BackendInstance getBackendInstance(String backendName) throws EiBackendInstancesException {
+        for(BackendInstance backendInstance: backendInstances) {
+            if(backendInstance.getName().equals(backendName)) {
+                LOG.debug("Returning backend " + backendName + ".");
+                return backendInstance;
+            }
+        }
+
+        throw new EiBackendInstancesException(
+                "EI Backend instance '" + backendName +  "' does not exist in EI Backend Instances list.");    }
```
Comment (tobiasake) [inline src/main/java/com/ericsson/ei/frontend/utils/BackEndInstancesHandler.java]: Move end bracket "}" to a new line.

File: src/main/resources/application.properties [hunk 6]
```diff
@@ -20,8 +20,8 @@ ei.use.secure.http.frontend=false
 
 ######## EI Default Back-Ends
 ei.backend.instances.filepath=
-ei.backend.instances.list.json.content=
-#ei.backend.instances.list.json.content=[{ "contextPath": "", "port": "8090", "name": "EI-Backend-1", "host": "localhost", "https": false, "defaultBackend": true}]
+#ei.backend.instances.list.json.content=
+ei.backend.instances.list.json.content=[{"name":"EI-Backend-1","host":"localhost","port":8070,"contextPath":"","https":false,"defaultBackend":true}, {"name":"EI-Backend-2","host":"localhost","port":8077,"contextPath":"","https":false,"defaultBackend":false}, {"name":"EI-Backend-3","host":"localhost","port":8078,"contextPath":"","https":false,"defaultBackend":true}]
```
Comment (tobiasake) [inline src/main/resources/application.properties]: Same comment here as earlier.

File: src/test/java/com/ericsson/ei/frontend/BackendInformationControllerUtilsTest.java [hunk 7]
```diff
@@ -40,9 +40,9 @@
 import org.springframework.http.ResponseEntity;
 import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
 
-import com.ericsson.ei.frontend.model.BackEndInformation;
+import com.ericsson.ei.frontend.model.BackendInstance;
 import com.ericsson.ei.frontend.utils.BackEndInformationControllerUtils;
-import com.ericsson.ei.frontend.utils.BackEndInstancesUtils;
+import com.ericsson.ei.frontend.utils.BackEndInstancesHandler;
```
Comment (tobiasake) [inline src/test/java/com/ericsson/ei/frontend/BackendInformationControllerUtilsTest.java]: You are mixing "BackeEnd" and "Backend" , I guess it should be "Backend".

File: src/functionaltest/java/com/ericsson/ei/frontend/pageobjects/SwitchBackendPage.java [hunk 8]
```diff
@@ -28,8 +28,8 @@ public SwitchBackendPage(CloseableHttpClient mockedHttpClient, FirefoxDriver dri
     public Object getInstanceNameAtPosition(int position) {
         new WebDriverWait(driver, TIMEOUT_TIMER)
                 .until(ExpectedConditions.presenceOfElementLocated(By.id("BackendInstance" + position + "Name")));
-        WebElement backendInstance1Name = driver.findElement(By.id("BackendInstance" + position + "Name"));
-        return backendInstance1Name.getText();
+        WebElement backendInstanceName = driver.findElement(By.id("BackendInstance" + position + "Name"));
```
Comment (a-breid-ericsson) [inline src/functionaltest/java/com/ericsson/ei/frontend/pageobjects/SwitchBackendPage.java]: This is an Element and not a Name.

File: src/integrationtest/resources/integration-test.properties (hunk 4 above)
Comment (a-breid-ericsson) [inline src/integrationtest/resources/integration-test.properties]: Do integration test use more then one back-end, if not the other ones may just be confusing to add.

File: src/functionaltest/resources/functional-test.properties (hunk 3 above)
Comment (a-breid-ericsson) [inline src/functionaltest/resources/functional-test.properties]: For readability you may split and indent this line a bit, I believe it will work anyway.

File: src/main/java/com/ericsson/ei/frontend/WebController.java [hunk 9]
```diff
@@ -56,7 +57,7 @@ public String testRules(Model model) {
     }
 
     @RequestMapping("/information.html")
-    public String info(Model model, HttpServletRequest request) {
+    public String info(Model model, HttpServletRequest request) throws EiBackendInstancesException {
```
Comment (a-breid-ericsson) [inline src/main/java/com/ericsson/ei/frontend/WebController.java]: What is EiBackendInstancesException and is it needed here?

File: src/main/java/com/ericsson/ei/frontend/utils/BackEndInformationControllerUtils.java [hunk 10]
```diff
@@ -31,16 +31,14 @@
...
-import com.google.gson.JsonParser;
 
 @Component
 public class BackEndInformationControllerUtils {
 
     private static final Logger LOG = LoggerFactory.getLogger(BackEndInformationControllerUtils.class);
 
     @Autowired
-    private BackEndInstancesUtils backEndInstancesUtils;
+    private BackEndInstancesHandler backEndInstancesUtils;
```
Comment (a-breid-ericsson) [inline src/main/java/com/ericsson/ei/frontend/utils/BackEndInformationControllerUtils.java]: Please rename variable.

File: src/main/java/com/ericsson/ei/frontend/utils/BackEndInformationControllerUtils.java [hunk 11]
```diff
@@ -31,16 +31,14 @@
 import org.springframework.stereotype.Component;
 
 import com.google.gson.JsonArray;
-import com.google.gson.JsonObject;
-import com.google.gson.JsonParser;
 
 @Component
 public class BackEndInformationControllerUtils {
```
Comment (a-breid-ericsson) [inline src/main/java/com/ericsson/ei/frontend/utils/BackEndInformationControllerUtils.java]: Please rename this class to for example BackEndInstanceControllerImpl.
Is this class needed? it has any logic?

File: src/main/java/com/ericsson/ei/frontend/utils/BackEndInformationControllerUtils.java [hunk 12]
```diff
@@ -52,7 +50,7 @@
      */
     public ResponseEntity<String> handleRequestForInstances(HttpServletRequest request) {
```
Comment (a-breid-ericsson) [inline src/main/java/com/ericsson/ei/frontend/utils/BackEndInformationControllerUtils.java]: Please rename method to getBackEndInstances or something.

File: src/integrationtest/resources/integration-test.properties (hunk 4 above)
Comment (e-edling-ericsson) [reply src/integrationtest/resources/integration-test.properties]: Removed this entirely, it shouldn't be here

Comment (e-edling-ericsson) [reply src/integrationtest/resources/integration-test.properties]: Removed them, they should not be here.

File: src/main/java/com/ericsson/ei/frontend/utils/BackEndInformationControllerUtils.java (hunk 11 above)
Comment (e-edling-ericsson) [reply src/main/java/com/ericsson/ei/frontend/utils/BackEndInformationControllerUtils.java]: It's not really an "impl" class as we don't implement an interface etc. I think that would be a confusion. But i agree that we should change its name.

File: src/main/java/com/ericsson/ei/frontend/utils/BackEndInformationControllerUtils.java (hunk 12 above)
Comment (e-edling-ericsson) [reply src/main/java/com/ericsson/ei/frontend/utils/BackEndInformationControllerUtils.java]: As it is implemented right now, getBackendInstances would be a lie as it actually creates a response based upon the retrieved backend instances. I don't want to create bigger refactoring at the moment but i think it should for example return backendinstances and then the controller should create the response object.

Comment (e-edling-ericsson) [reply src/main/java/com/ericsson/ei/frontend/utils/BackEndInformationControllerUtils.java]: I will add a refactoring story about this together with whats mentioned above.

File: src/functionaltest/resources/functional-test.properties [hunk 13]
```diff
@@ -1,4 +1,6 @@
 test.selenium.firefox.BZip2File.url.linux = https://ftp.mozilla.org/pub/firefox/releases/61.0.1/linux-x86_64/en-GB/firefox-61.0.1.tar.bz2
-ei.backend.instances.list.json.content=[{"name":"EI-Backend-1","host":"localhost","port":8070,"contextPath":"","https":false,"defaultBackend":true}, {"name":"EI-Backend-2","host":"localhost","port":8077,"contextPath":"","https":false,"defaultBackend":false}, {"name":"EI-Backend-3","host":"localhost","port":8078,"contextPath":"","https":false,"defaultBackend":true}]
+ei.backend.instances.list.json.content=[{"name":"EI-Backend-1","host":"localhost","port":8070,"contextPath":"","https":false,"defaultBackend":true}, \
```
Comment (tobiasake) [inline src/functionaltest/resources/functional-test.properties]: A lot of white spaces here,, or does just looks strange in the review view.

File: src/functionaltest/java/com/ericsson/ei/frontend/SeleniumBaseClass.java [hunk 14]
```diff
@@ -52,15 +52,17 @@ public void setUp() throws Exception {
 
     @After
     public void tearDown() throws Exception {
+        if (driver != null) {
+            driver.quit();
```
Comment (SantoshNC68) [inline src/functionaltest/java/com/ericsson/ei/frontend/SeleniumBaseClass.java]: may be add the logger with a proper quit message

File: src/main/java/com/ericsson/ei/frontend/utils/BackendInformationControllerImpl.java [hunk 15]
```diff
@@ -0,0 +1,95 @@
...
+            String selectedInstanceName = request.getReader().lines().collect(Collectors.joining(System.lineSeparator()));
+            request.getSession().setAttribute("backEndInstanceName", selectedInstanceName);
+
+            return new ResponseEntity<>(
+                    "{\"message\": \"Backend instance with name '" + selectedInstanceName + "' was selected.\"}",
+                    getHeaders(), HttpStatus.OK);
+        } catch (Exception e) {
+            LOG.error("Error while switching instance: " + e.getMessage());
+            String response = "{\"message\": \"Internal Error: " + e.getMessage() + "\"}";
+            return new ResponseEntity<>(response, getHeaders(), HttpStatus.INTERNAL_SERVER_ERROR);
```
Comment (SantoshNC68) [inline src/main/java/com/ericsson/ei/frontend/utils/BackendInformationControllerImpl.java]: Will it always be an Internal Server Error? Does the backend need authentication? If so what happens when it get bad credentials or other error messages?

File: src/functionaltest/resources/functional-test.properties (hunk 13 above)
Comment (e-edling-ericsson) [reply src/functionaltest/resources/functional-test.properties]: I've indented this like the EI Documentation url below. It might look a bit wierd in the github code review

File: src/main/java/com/ericsson/ei/frontend/utils/BackendInformationControllerImpl.java (hunk 15 above)
Comment (e-edling-ericsson) [reply src/main/java/com/ericsson/ei/frontend/utils/BackendInformationControllerImpl.java]: I don't know why git says i've changed this method. This is not something i changed or want to change in this PR. I've done too much refactoring :) This change might affect tests as other return statuses would be created.

File: src/functionaltest/resources/functional-test.properties (hunk 13 above)
Comment (tobiasake) [reply src/functionaltest/resources/functional-test.properties]: ok

File: src/main/java/com/ericsson/ei/frontend/utils/BackendInformationControllerUtils.java [hunk 16]
```diff
@@ -0,0 +1,95 @@
...
+import org.springframework.http.HttpHeaders;
+import org.springframework.http.HttpStatus;
+import org.springframework.http.MediaType;
+import org.springframework.http.ResponseEntity;
+import org.springframework.stereotype.Component;
+
+import com.google.gson.JsonArray;
+
+@Component
+public class BackendInformationControllerUtils {
```
Comment (a-breid-ericsson) [inline src/main/java/com/ericsson/ei/frontend/utils/BackendInformationControllerUtils.java]: You may remove the Utils part of the name since the package is utils

File: src/main/java/com/ericsson/ei/frontend/utils/BackendInformationControllerUtils.java [hunk 17]
```diff
@@ -0,0 +1,95 @@
...
+    }
+
+    /**
+     * Processes requests to switch back end, and sets the back end name to a session variable that is
+     * kept for current session.
+     *
+     * @param request
+     * @return new ResponseEntity
+     */
+    public ResponseEntity<String> handleRequestToSwitchBackEnd(HttpServletRequest request) {
```
Comment (a-breid-ericsson) [inline src/main/java/com/ericsson/ei/frontend/utils/BackendInformationControllerUtils.java]: Switch back end is never done here... Since the selected back end is stored in the browser only.

File: src/main/java/com/ericsson/ei/frontend/utils/BackendInformationControllerUtils.java [hunk 18]
```diff
@@ -0,0 +1,95 @@
...
+                    "{\"message\": \"Backend instance with name '" + selectedInstanceName + "' was selected.\"}",
+                    getHeaders(), HttpStatus.OK);
+        } catch (Exception e) {
+            LOG.error("Error while switching instance: " + e.getMessage());
+            String response = "{\"message\": \"Internal Error: " + e.getMessage() + "\"}";
+            return new ResponseEntity<>(response, getHeaders(), HttpStatus.INTERNAL_SERVER_ERROR);
+        }
+    }
+
+    private HttpHeaders getHeaders() {
```
Comment (a-breid-ericsson) [inline src/main/java/com/ericsson/ei/frontend/utils/BackendInformationControllerUtils.java]: This method creates headers.

File: src/main/java/com/ericsson/ei/frontend/utils/BackendInformationControllerUtils.java [hunk 19]
```diff
@@ -0,0 +1,95 @@
...
+
+    /**
+     * Processes a request to get all available back ends and returns
+     * data containing all back end instances with added information
+     * weather a back end is set as active or not.
+     *
+     * @param request
+     * @return new ResponseEntity
+     */
+    public ResponseEntity<String> handleRequestForInstances(HttpServletRequest request) {
```
Comment (a-breid-ericsson) [inline src/main/java/com/ericsson/ei/frontend/utils/BackendInformationControllerUtils.java]: getBackendInstancesResponse is a better name.

File: src/main/java/com/ericsson/ei/frontend/utils/BackendInstancesHandler.java [hunk 20]
```diff
@@ -0,0 +1,143 @@
...
+    }
+
+    /**
+     * Sets the backendInstances list, useful when mocking for tests
+     *
+     * @param backendInstances
+     */
+    public void setBackendInstances(JsonArray backendInstances) {
+        cleanBackendInstances();
+        backendInstancesJsonString = backendInstances.toString();
```
Comment (a-breid-ericsson) [inline src/main/java/com/ericsson/ei/frontend/utils/BackendInstancesHandler.java]: Do backendInstancesJsonString has to be a global variable or is it only used here and in parse String?, One may send the parsed string to 'parseBackendInstancesStringToBackendInstances'.

The function parseBackendInstancesStringToBackendInstances could be named 'setBackendInstances' as it is what it does, but instead recieve a string.

Heck it actually convers a JsonArray to String, then converts the String to a JsonArray...

File: src/main/java/com/ericsson/ei/frontend/utils/BackendInstancesHandler.java [hunk 21]
```diff
@@ -0,0 +1,143 @@
...
+    private void parseBackendInstancesStringToBackendInstances() {
+        try {
+            if(backendInstancesJsonString == null && backendInstancesJsonString.isEmpty()) {
+                LOG.debug("No backend instances provided.");
+                return;
+            }
+
+            JSONArray backendInstancesJsonArray = new JSONArray(backendInstancesJsonString);
+            for(Object jsonElement: backendInstancesJsonArray) {
+                JSONObject backendInstanceJsonObject = (JSONObject)jsonElement;
```
Comment (a-breid-ericsson) [inline src/main/java/com/ericsson/ei/frontend/utils/BackendInstancesHandler.java]: Is it not possible to make it a JsonObject in the for statement and not first an Object?

File: src/main/java/com/ericsson/ei/frontend/utils/EIRequestsControllerUtils.java [hunk 22]
```diff
@@ -50,7 +50,7 @@
     private static final String BACKEND_NAME_KEY_NAME = "backendname";
 
     @Autowired
-    private BackEndInstancesUtils backEndInstancesUtils;
+    private BackendInstancesHandler backEndInstancesUtils;
```
Comment (a-breid-ericsson) [inline src/main/java/com/ericsson/ei/frontend/utils/EIRequestsControllerUtils.java]: Please rename the variable.

File: src/main/java/com/ericsson/ei/frontend/utils/BackendInformationControllerImpl.java (hunk 15 above)
Comment (Christoffer-Cortes) [reply src/main/java/com/ericsson/ei/frontend/utils/BackendInformationControllerImpl.java]: The backend switch only takes place in the frontend and doesn't require authentication. I guess it's just a lazy way of catching any potential error caused.

File: src/main/java/com/ericsson/ei/frontend/utils/EIRequestsControllerUtils.java [hunk 23]
```diff
@@ -90,24 +90,40 @@ private String getBackEndUrl(String requestQuery) throws EiBackendInstancesExcep
...
                 requestUrl = extractUrlFromParameters(params);
-            } else {
-                String backEndName = extractBackEndNameFromParameters(params);
-                BackEndInformation backEndInformation = backEndInstancesUtils.getBackEndInformationByName(backEndName);
-                if (backEndInformation == null) {
-                    throw new EiBackendInstancesException(
-                            "EI Backend instance '" + backEndName +  "' does not exist in EI Backend Instances list.");
+            } else if(requestQuery.contains(BACKEND_NAME_KEY_NAME)) {
+                try {
+                    requestUrl = getUrlFromBackendInstancesUtils(params);
```
Comment (a-breid-ericsson) [inline src/main/java/com/ericsson/ei/frontend/utils/EIRequestsControllerUtils.java]: Imagine the scenaria when a user selects a back-end that does not exist and he creates a subscription in the default one and not the selected one. Should this be possible?

File: src/main/java/com/ericsson/ei/frontend/utils/EIRequestsControllerUtils.java [hunk 24]
```diff
@@ -90,24 +90,40 @@ private String getBackEndUrl(String requestQuery) throws EiBackendInstancesExcep
...
     }
 
+    private String getUrlFromBackendInstancesUtils(List<NameValuePair> params) throws EiBackendInstancesException {
+        String backEndName = extractBackEndNameFromParameters(params);
+        BackendInstance backendInstance = backEndInstancesUtils.getBackendInstance(backEndName);
+        if (backendInstance == null) {
+            throw new EiBackendInstancesException(
+                    "EI Backend instance '" + backEndName +  "' does not exist in EI Backend Instances list.");
+        }
+        return backendInstance.getUrlAsString();
```
Comment (a-breid-ericsson) [inline src/main/java/com/ericsson/ei/frontend/utils/EIRequestsControllerUtils.java]: I would prefer getUrl().toString()
There is 2 operations in one method.

File: src/main/java/com/ericsson/ei/frontend/utils/WebControllerUtils.java [hunk 25]
```diff
@@ -63,7 +64,7 @@
     private String applicationName;
 
     @Autowired
-    private BackEndInstancesUtils backEndInstancesUtils;
+    private BackendInstancesHandler backEndInstancesUtils;
```
Comment (a-breid-ericsson) [inline src/main/java/com/ericsson/ei/frontend/utils/WebControllerUtils.java]: Please rename variable.

File: src/main/resources/application.properties [hunk 26]
```diff
@@ -20,8 +20,10 @@ ei.use.secure.http.frontend=false
 
 ######## EI Default Back-Ends
 ei.backend.instances.filepath=
-ei.backend.instances.list.json.content=
-#ei.backend.instances.list.json.content=[{ "contextPath": "", "port": "8090", "name": "EI-Backend-1", "host": "localhost", "https": false, "defaultBackend": true}]
+#ei.backend.instances.list.json.content=
+ei.backend.instances.list.json.content=[{"name":"EI-Backend-1","host":"localhost","port":8070,"contextPath":"","https":false,"defaultBackend":true},\
```
Comment (a-breid-ericsson) [inline src/main/resources/application.properties]: Please revert changes here.

File: src/test/java/com/ericsson/ei/frontend/BackEndInformationTest.java [hunk 27]
```diff
@@ -43,13 +43,13 @@
     private static final String BACK_END_HOST = "Test_host";
     private static final String BACK_END_PORT = "12345";
 
-    private BackEndInformation backEndInformation;
+    private BackendInstance backEndInformation;
```
Comment (a-breid-ericsson) [inline src/test/java/com/ericsson/ei/frontend/BackEndInformationTest.java]: Please rename variable.

File: src/functionaltest/java/com/ericsson/ei/frontend/TestRulesFunctionality.java [hunk 28]
```diff
@@ -51,9 +52,9 @@
 
     @Before
     public void before() throws IOException {
-        int serverPort = mockServer.getLocalPort();
-        backEndInstancesUtils.setDefaultBackEndInstanceToNull();
-        backEndInstancesUtils.setDefaultBackEndInstance("new_instance_default", "localhost", serverPort, "", true);
+        int portServer = mockServer.getLocalPort();
```
[the remark this answers is not in the document]
Comment (e-edling-ericsson) [reply src/functionaltest/java/com/ericsson/ei/frontend/TestRulesFunctionality.java]: Done

File: src/main/java/com/ericsson/ei/frontend/utils/BackendInstancesHandler.java (hunk 20 above)
Comment (e-edling-ericsson) [reply src/main/java/com/ericsson/ei/frontend/utils/BackendInstancesHandler.java]: backendInstancesJsonString is read from application.properties so it has to be a private variable.

I don't quite agree with the reasoning behind parseBackendInstancesStringToBackendInstances. There is already a method named setBackendInstances, that method has a helper method to parse the instances from the private variable of instances that has string format to the BackendInstances object, that is it's main objective. Then the helper method itself is doing stuff within it yes but the main objective is to parse from a structure into another.

File: src/functionaltest/java/com/ericsson/ei/frontend/TestRulesFunctionality.java [hunk 29]
```diff
@@ -75,6 +76,8 @@ public void testJourneyToFindAggregatedObjectButton() throws Exception {
     public static void setUpMocks() throws IOException {
         mockServer = startClientAndServer();
         mockClient = new MockServerClient(BASE_URL, mockServer.getLocalPort());
+        mockClient.when(request().withMethod("GET").withPath("/auth/checkStatus"))
+        .respond(response().withStatusCode(200));
```
[the remark this answers is not in the document]
Comment (e-edling-ericsson) [reply src/functionaltest/java/com/ericsson/ei/frontend/TestRulesFunctionality.java]: done

File: src/main/java/com/ericsson/ei/frontend/utils/BackendInformationControllerUtils.java (hunk 16 above)
Comment (e-edling-ericsson) [reply src/main/java/com/ericsson/ei/frontend/utils/BackendInformationControllerUtils.java]: But it's not a controller either. This part as i mentioned before should be refactored with both name and functionality later.

Comment (SantoshNC68) [reply src/main/java/com/ericsson/ei/frontend/utils/BackendInformationControllerUtils.java]: I guess we can keep the Utils in the className. since it is a utility package we can have n number of utils classes.

File: src/main/java/com/ericsson/ei/frontend/utils/BackendInformationControllerUtils.java (hunk 17 above)
Comment (e-edling-ericsson) [reply src/main/java/com/ericsson/ei/frontend/utils/BackendInformationControllerUtils.java]: I haven't made any changes in this file besides removing old functionality and changing filename.

Comment (e-edling-ericsson) [reply src/main/java/com/ericsson/ei/frontend/utils/BackendInformationControllerUtils.java]: I just changed name for this file, i haven't really done any changes besides removing functionality for add/remove. I don't want to refactor more than necessary because this PR is already big.

File: src/main/java/com/ericsson/ei/frontend/utils/BackendInformationControllerUtils.java (hunk 18 above)
Comment (e-edling-ericsson) [reply src/main/java/com/ericsson/ei/frontend/utils/BackendInformationControllerUtils.java]: done

File: src/main/java/com/ericsson/ei/frontend/utils/BackendInformationControllerUtils.java (hunk 19 above)
Comment (e-edling-ericsson) [reply src/main/java/com/ericsson/ei/frontend/utils/BackendInformationControllerUtils.java]: agreed, done

File: src/main/java/com/ericsson/ei/frontend/utils/BackendInstancesHandler.java (hunk 21 above)
Comment (e-edling-ericsson) [reply src/main/java/com/ericsson/ei/frontend/utils/BackendInstancesHandler.java]: Nope sorry. doesnt work :(

File: src/main/java/com/ericsson/ei/frontend/utils/EIRequestsControllerUtils.java (hunk 22 above)
Comment (e-edling-ericsson) [reply src/main/java/com/ericsson/ei/frontend/utils/EIRequestsControllerUtils.java]: done

File: src/main/java/com/ericsson/ei/frontend/utils/EIRequestsControllerUtils.java (hunk 23 above)
Comment (e-edling-ericsson) [reply src/main/java/com/ericsson/ei/frontend/utils/EIRequestsControllerUtils.java]: That is how the functionality worked before. I didn't want to change too much in the behaviour in the refactoring.

File: src/main/java/com/ericsson/ei/frontend/utils/EIRequestsControllerUtils.java (hunk 24 above)
Comment (e-edling-ericsson) [reply src/main/java/com/ericsson/ei/frontend/utils/EIRequestsControllerUtils.java]: This is functionality from before as well, i dont want to refactor it now either.

File: src/main/java/com/ericsson/ei/frontend/utils/WebControllerUtils.java (hunk 25 above)
Comment (e-edling-ericsson) [reply src/main/java/com/ericsson/ei/frontend/utils/WebControllerUtils.java]: done

File: src/main/resources/application.properties (hunk 26 above)
Comment (e-edling-ericsson) [reply src/main/resources/application.properties]: done

File: src/test/java/com/ericsson/ei/frontend/BackEndInformationTest.java (hunk 27 above)
Comment (e-edling-ericsson) [reply src/test/java/com/ericsson/ei/frontend/BackEndInformationTest.java]: done
